// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture3D<float4> MainTex;
RWTexture2D<float4> Result;
int Slice;
bool Inverse;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint3 pos = uint3(id.x, id.y, Slice);
    float4 col = MainTex[pos];
    if (Inverse) {
        col = 1 - col;
    }
	Result[id.xy] = col;
}
